
# 
# DO NOT EDIT THIS FILE!
# It will be overwriten by ant.
#
HouseMonitorVersion='4.0.3'
HouseMonitorAuthor='Gary Pickens'
HouseMonitorEmail='gary_pickens@yahoo.com'    		
HouseMonitorBuildDate='2013-05-06 22:34:11'
HouseMonitorTitle='House Monitor and Control'
HouseMonitorProject='HouseMonitor'
    	